# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-21 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EndLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UNIT', models.IntegerField(blank=True, null=True)),
                ('LINE_ID', models.IntegerField(blank=True, null=True)),
                ('TEMPERATURE', models.IntegerField(blank=True, null=True)),
                ('SENSOR', models.IntegerField(blank=True, null=True)),
                ('RADIO_STATION', models.IntegerField(blank=True, null=True)),
                ('BATTERY', models.IntegerField(blank=True, null=True)),
                ('TIME', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '\u5c3d\u5934\u7ebf\u4fe1\u606f',
                'verbose_name_plural': '\u5c3d\u5934\u7ebf\u4fe1\u606f',
            },
        ),
    ]
