# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-21 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_line', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endline',
            name='BATTERY',
            field=models.IntegerField(blank=True, choices=[(0, '\u5f02\u5e38'), (1, '\u6b63\u5e38')], null=True, verbose_name='\u7535\u6c60'),
        ),
        migrations.AlterField(
            model_name='endline',
            name='RADIO_STATION',
            field=models.IntegerField(blank=True, choices=[(0, '\u5f02\u5e38'), (1, '\u6b63\u5e38')], null=True, verbose_name='\u7535\u53f0'),
        ),
        migrations.AlterField(
            model_name='endline',
            name='SENSOR',
            field=models.IntegerField(blank=True, choices=[(0, '\u5f02\u5e38'), (1, '\u6b63\u5e38')], null=True, verbose_name='\u4f20\u611f\u5668'),
        ),
        migrations.AlterField(
            model_name='endline',
            name='TEMPERATURE',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u6e29\u5ea6'),
        ),
        migrations.AlterField(
            model_name='endline',
            name='TIME',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='endline',
            name='UNIT',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u5355\u4f4d'),
        ),
    ]
